### ISSUE TITLE
Integrate Play Now Games with Custom Room Games

### ISSUE THREAD

**Issue by tedhyu** [tridecco/game-client-web#58]
When I click play now and the criteria I have (for example, 2 player, multi-round) matches the criteria of a room in custom room:

I should join that game.  The play now and Start game menu should be ablet to join each other.

Presently, if there's a 2 player, multi-round game in custom room, and I click play now with those criteria, I don't join that game.

**Comment by TKanX** [comment]
If you really want this feature to work in the current version (v0.x.x), maybe I can implement a patch in the game client that checks if there is an empty room that matches the game mode before joining the queue. This feature may be unstable because the underlying logic of the current version does not support it, so it will cause some limitations and performance issues. For example, you can only join rooms that match the game mode created before clicking "Play Now".
